export const ACTION_REGISTER_BEGIN_PURCHASE = 'ACTION_REGISTER_BEGIN_PURCHASE';
export const ACTION_GET_CONFIGURATION = 'ACTION_GET_CONFIGURATION';
export const ACTION_EMULATE_PAYMENT = 'ACTION_EMULATE_PAYMENT';
export const ACTION_GET_ORDER = 'ACTION_GET_ORDER';

export const ACTION_GET_CATALOG = 'ACTION_GET_CATALOG';
export const ACTION_REFRESH_CATALOG = 'ACTION_REFRESH_CATALOG';
