export const ROUTE_HOME = 'ROUTE_HOME';
export const ROUTE_PAYMENT_SERVICE_EMULATION = 'ROUTE_PAYMENT_SERVICE_EMULATION';
export const ROUTE_GET_ORDER = 'ROUTE_GET_ORDER';
export const ROUTE_PAYMENT_ERROR = 'ROUTE_PAYMENT_ERROR';
